### ISSUE TITLE
Responsive Bug

### ISSUE THREAD

**Issue by peymanath** [nafasebra/nafasebra-portfolio#1]
سلام :) توضیحات این باگ رو به زبان فارسی بیان میکنم ... ترجمه به انگلیسی زمانبر بود.

در سکشن مربوط به Blog به خاطر گودی های متحرکت مشکل رسپانسیو دارید طبق بررسی هایی که داشتم میتونید با Overflow-Hiden دادن به سکشن مربوطه این مشکل رو حل کنید. وقتی با موبایل دیدم خاطرم بود که این موضوعو در گیت هاب بگم که باگشو فیکس کنید.

سپاس از توجه شما :)

**Comment by nafasebra** [comment]
سلام مرسی بابت ارسال issue ت :)
حتما سرفرصت چکش کنم
