### ISSUE TITLE
A bug in automatically scrolling using the navbar buttons.

### ISSUE THREAD

**Issue by mazdakdev** [nafasebra/nafasebra-portfolio#2]
When one is viewing your blog posts and meanwhile attempting to move to another section like "نمونه کار ها", The CSS ID of that element appends to the current URL rather than to the root URL. Hence no change will occur.

## Steps To Reproduce
1. Visit www.nafasebra.ir.
2. Proceed to the blog section.
3. Click on a blog post such as : "فرق برنامه نویسی و کد نویسی".
4. Click on a navbar button such as "مهارت ها".

**Comment by nafasebra** [comment]
Thanks for sharing troubleshoots 🙏
